# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82e4b084da221b141847dae9dcefb92b79cee12f9bbcd17edac43eebb9756f350e80149700ec9d38fbcb4a8c1829d47c2ae3a7cb767d1c302b7b24c3e38e126f
  redis:
    url: <%= ENV["REDIS_URL"] || 'redis://localhost:6379/0' %>
    namespaces:
      cache: <%= ENV["REDIS_NAMESPACES_CACHE"] || 'cache' %>
      search: <%= ENV["REDIS_NAMESPACES_SEARCH"] || 'search' %>

test:
  secret_key_base: 0d9241dc6e9e5793543e3564829d2f3de4548f981f59c7851e03860f7624bbb8dfb7bd46b616a1ae5f8710e12b44dacaf5e307fdc605fa0a57e0b95c8af15a87
  redis:
    url: <%= ENV["REDIS_URL"] || 'redis://localhost:6379/0' %>
    namespaces:
      cache: <%= ENV["REDIS_NAMESPACES_CACHE"] || 'cache' %>
      search: <%= ENV["REDIS_NAMESPACES_SEARCH"] || 'search' %>

# Deployment template for production secrets.  Our deployment scripts use this template
# to populate secrets into the AWS Parameter Store so that they can later be read by
# spun up instances and populated back into the deployed version of this file.  Note
# that generally-speaking this template is only used when an entire environment is
# created, at which point things like "random(hex,80)" are used to generate a random
# hex key in the parameter store.  The nested key structure of this template gets
# embedded in key names in the parameter store and those structured key names are
# later converted back to the nested YAML secrets needed in this file.  See
# lib/tasks/install_secrets.rake for more information.

production:
  secret_key_base: random(hex,80)
  base_url: "https://{{ domain }}"
  database:
    host: "{{ database_host }}"
    port: "{{ database_port }}"
    username: "{{ database_username }}"
    password: "{{ database_password }}"
    name: "{{ database_name }}"
  redis:
    url: "{{ redis_url }}"
    namespaces:
      cache: "metadata-{{ env_name }}-cache"
      search: "metadata-{{ env_name }}-search"
